1. Load the dataset and handle any missing data by replacing null values with the mean
value of the respective column.

In [25]:
import pandas as pd
import numpy as np

dataSet = pd.read_csv("winequality-red.csv", sep =";")
display(dataSet.head())

print(dataSet.isnull().sum())

dataSet = dataSet.fillna(dataSet.mean(numeric_only=True))
display(dataSet) 

print("Missing values after filling:")
print(dataSet.isnull().sum())

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

Missing values after filling:
fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

2. Extract the following columns as vectors: alcohol,citric acid.

In [12]:
alcohol_vector = dataSet["alcohol"].to_numpy()
citric_vector = dataSet["citric acid"].to_numpy()
print("Alcohol Vector:" ,alcohol_vector)
print("Citric Acid Vector:",citric_vector)

Alcohol Vector: [ 9.4  9.8  9.8 ... 11.  10.2 11. ]
Citric Acid Vector: [0.   0.   0.04 ... 0.13 0.12 0.47]
Shape (1599,)

3. Select two features (e.g., alcohol and density) from the dataset and calculate the
covariance matrix using np.cov(X.T), where X is the feature matrix consisting of the
selected columns.

In [15]:
X = dataSet[["alcohol", "density"]].to_numpy()
covariance_matrix = np.cov(X.T)
print("Covariance Matrix: \n", covariance_matrix)

Covariance Matrix:
 [[ 1.13564740e+00 -9.97951790e-04]
 [-9.97951790e-04  3.56202945e-06]]

4. Perform eigen decomposition on the covariance matrix,results:Identify the top 2 eigenvalues,Identify the corresponding eigenvectors.

In [17]:
eigenValues, eigenVectors = np.linalg.eigh(covariance_matrix)
indices = np.argsort(eigenValues)[::-1]
eigenValues = eigenValues[indices]
eigenVectors = eigenVectors[:, indices]
print("Top 2 Eigenvalues:")
print(eigenValues[:2])

Top 2 Eigenvalues:
[1.13564827e+00 2.68507580e-06]

5. Most common wine quality in the dataset and interpret distribution of wine quality scores.

In [24]:
qualityScore_count = dataSet["quality"].value_counts().sort_index()
print("The distribution of wine quality:",qualityScore_count)

mostCommon_quality = dataSet["quality"].mode()[0]
mostCommon_count = dataSet["quality"].value_counts().max()

print("Most common wine quality:", mostCommon_quality)
print("Number of wines:", mostCommon_count)

percentage = (mostCommon_count / len(dataSet)) * 100

roundPercent = percentage.round(2)

print("Percentage:",roundPercent)

The distribution of wine quality: quality
3     10
4     53
5    681
6    638
7    199
8     18
Name: count, dtype: int64
Most common wine quality: 5
Number of wines: 681
Percentage: 42.59